gua:
- { id: 1 ,name: 乾 ,mx: 11 ,alias: 乾为天 }
- { id: 2 ,name: 坤 ,mx: 88 ,alias: 坤为地 }
- { id: 3 ,name: 屯 ,mx: 64 ,alias: 水雷屯zhun1 }
- { id: 4 ,name: 蒙 ,mx: 76 ,alias: 山水蒙 }
- { id: 5 ,name: 需 ,mx: 61 ,alias: 水天需 }
- { id: 6 ,name: 訟 ,mx: 16 ,alias: 天水讼 }
- { id: 7 ,name: 師 ,mx: 86 ,alias: 地水师 }
- { id: 8 ,name: 比 ,mx: 68 ,alias: 水地比 }
- { id: 9 ,name: 小畜 ,mx: 51 ,alias: 风天小畜 }
- { id: 10 ,name: 履 ,mx: 12 ,alias: 天泽履 }
- { id: 11 ,name: 泰 ,mx: 81 ,alias: 地天泰 }
- { id: 12 ,name: 否 ,mx: 18 ,alias: 天地否 }
- { id: 13 ,name: 同人 ,mx: 13 ,alias: 天火同人 }
- { id: 14 ,name: 大有 ,mx: 31 ,alias: 火天大有 }
- { id: 15 ,name: 謙 ,mx: 87 ,alias: 地山谦 }
- { id: 16 ,name: 豫 ,mx: 48 ,alias: 雷地豫 }
- { id: 17 ,name: 隨 ,mx: 24 ,alias: 泽雷隨 }
- { id: 18 ,name: 蠱 ,mx: 75 ,alias: 山风蠱gu3 }
- { id: 19 ,name: 臨 ,mx: 82 ,alias: 地泽臨 }
- { id: 20 ,name: 觀 ,mx: 58 ,alias: 风地觀 }
- { id: 21 ,name: 噬嗑 ,mx: 34 ,alias: 火雷噬瞌 }
- { id: 22 ,name: 賁 ,mx: 73 ,alias: 山火贲bi4 }
- { id: 23 ,name: 剝 ,mx: 78 ,alias: 山地剥 }
- { id: 24 ,name: 復 ,mx: 84 ,alias: 地雷復 }
- { id: 25 ,name: 無妄 ,mx: 14 ,alias: 天雷無妄 }
- { id: 26 ,name: 大畜 ,mx: 71 ,alias: 山天大畜 }
- { id: 27 ,name: 頤 ,mx: 74 ,alias: 山雷頤 }
- { id: 28 ,name: 大過 ,mx: 25 ,alias: 泽风大過 }
- { id: 29 ,name: 坎 ,mx: 66 ,alias: 坎为水 }
- { id: 30 ,name: 離 ,mx: 33 ,alias: 離为火 }
- { id: 31 ,name: 咸 ,mx: 27 ,alias: 泽山咸 }
- { id: 32 ,name: 恆 ,mx: 46 ,alias: 雷风恒 }
- { id: 33 ,name: 遯 ,mx: 17 ,alias: 天山遯 }
- { id: 34 ,name: 大壯 ,mx: 41 ,alias: 雷天大壮 }
- { id: 35 ,name: 晉 ,mx: 38 ,alias: 火地晉 }
- { id: 36 ,name: 明夷 ,mx: 83 ,alias: 地火明夷 }
- { id: 37 ,name: 家人 ,mx: 53 ,alias: 风火家人 }
- { id: 38 ,name: 睽 ,mx: 32 ,alias: 火泽睽 }
- { id: 39 ,name: 蹇 ,mx: 67 ,alias: 水山蹇 }
- { id: 40 ,name: 解 ,mx: 46 ,alias: 雷水解 }
- { id: 41 ,name: 損 ,mx: 72 ,alias: 山泽損 }
- { id: 42 ,name: 益 ,mx: 54 ,alias: 风雷益 }
- { id: 43 ,name: 夬 ,mx: 21 ,alias: 泽天夬guai4 }
- { id: 44 ,name: 姤 ,mx: 15 ,alias: 天风姤 }
- { id: 45 ,name: 萃 ,mx: 28 ,alias: 泽地萃 }
- { id: 46 ,name: 升 ,mx: 85 ,alias: 地风升 }
- { id: 47 ,name: 困 ,mx: 26 ,alias: 泽水困 }
- { id: 48 ,name: 井 ,mx: 65 ,alias: 水风井 }
- { id: 49 ,name: 革 ,mx: 23 ,alias: 泽火革 }
- { id: 50 ,name: 鼎 ,mx: 35 ,alias: 火风鼎 }
- { id: 51 ,name: 震 ,mx: 44 ,alias: 震为雷 }
- { id: 52 ,name: 艮 ,mx: 77 ,alias: 艮为山 }
- { id: 53 ,name: 漸 ,mx: 57 ,alias: 风山漸 }
- { id: 54 ,name: 歸妹 ,mx: 42 ,alias: 雷泽歸妹 }
- { id: 55 ,name: 豐 ,mx: 43 ,alias: 雷火豐 }
- { id: 56 ,name: 旅 ,mx: 37 ,alias: 火山旅 }
- { id: 57 ,name: 巽 ,mx: 55 ,alias: 巽为风 }
- { id: 58 ,name: 兌 ,mx: 22 ,alias: 兑为泽 }
- { id: 59 ,name: 渙 ,mx: 56 ,alias: 风水渙 }
- { id: 60 ,name: 節 ,mx: 62 ,alias: 水泽節 }
- { id: 61 ,name: 中孚 ,mx: 52 ,alias: 风泽中孚 }
- { id: 62 ,name: 小過 ,mx: 47 ,alias: 雷山小過 }
- { id: 63 ,name: 既濟 ,mx: 63 ,alias: 水火既濟 }
- { id: 64 ,name: 未濟 ,mx: 36 ,alias: 火水未濟 }
